// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Sf9R8s0gJHJNrO-9RJEhKfHFrUXFWbk',
    appId: '1:560414122188:web:0c47c036ef32c987482269',
    messagingSenderId: '560414122188',
    projectId: 'budgeting-app-85c2c',
    authDomain: 'budgeting-app-85c2c.firebaseapp.com',
    storageBucket: 'budgeting-app-85c2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuvILOyRbYatLGj9ExQ3mkpdC9VqVOOig',
    appId: '1:560414122188:android:a2c54ef7cc9a1602482269',
    messagingSenderId: '560414122188',
    projectId: 'budgeting-app-85c2c',
    storageBucket: 'budgeting-app-85c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQJZaqsNPUl1lYnj3cr7yrjjoHWsdmH4',
    appId: '1:560414122188:ios:fbcc19651480026c482269',
    messagingSenderId: '560414122188',
    projectId: 'budgeting-app-85c2c',
    storageBucket: 'budgeting-app-85c2c.firebasestorage.app',
    iosClientId: '560414122188-ij66fca1nkmsk4iaee75o6n3p3avp199.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnQJZaqsNPUl1lYnj3cr7yrjjoHWsdmH4',
    appId: '1:560414122188:ios:fbcc19651480026c482269',
    messagingSenderId: '560414122188',
    projectId: 'budgeting-app-85c2c',
    storageBucket: 'budgeting-app-85c2c.firebasestorage.app',
    iosClientId: '560414122188-ij66fca1nkmsk4iaee75o6n3p3avp199.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Sf9R8s0gJHJNrO-9RJEhKfHFrUXFWbk',
    appId: '1:560414122188:web:8d0c6acfc8440580482269',
    messagingSenderId: '560414122188',
    projectId: 'budgeting-app-85c2c',
    authDomain: 'budgeting-app-85c2c.firebaseapp.com',
    storageBucket: 'budgeting-app-85c2c.firebasestorage.app',
  );

}